// AUTO‑GENERATED – DO NOT EDIT
// Generated by scripts/generate-decks.js

const dev = import.meta.env.DEV

export default [
  {
    id: "2025-11-19_intro-rdm",
    title: "2025-11-19_intro-rdm",
    description: "",
    author: "Unknown",
    date: "1970-01-01",
    url: dev
      ? "http://localhost:3030"
      : "/2025-11-19_intro-rdm/"
  },
  {
    id: "2025-12-04_arc",
    title: "2025-12-04_arc",
    description: "",
    author: "Unknown",
    date: "1970-01-01",
    url: dev
      ? "http://localhost:3031"
      : "/2025-12-04_arc/"
  },
  {
    id: "2025-12-12_wfls",
    title: "2025-12-12_wfls",
    description: "",
    author: "Unknown",
    date: "1970-01-01",
    url: dev
      ? "http://localhost:3032"
      : "/2025-12-12_wfls/"
  },
  {
    id: "2026-01-14_cwl-handsOn",
    title: "2026-01-14_cwl-handsOn",
    description: "",
    author: "Unknown",
    date: "1970-01-01",
    url: dev
      ? "http://localhost:3033"
      : "/2026-01-14_cwl-handsOn/"
  },
  {
    id: "2026-02-11_arcify",
    title: "2026-02-11_arcify",
    description: "",
    author: "Unknown",
    date: "1970-01-01",
    url: dev
      ? "http://localhost:3034"
      : "/2026-02-11_arcify/"
  },
  {
    id: "2026-03-24_fdm-werkstatt",
    title: "2026-03-24_fdm-werkstatt",
    description: "",
    author: "Unknown",
    date: "1970-01-01",
    url: dev
      ? "http://localhost:3035"
      : "/2026-03-24_fdm-werkstatt/"
  }
]
