import fs from 'fs'
import path from 'path'

const ROOT = process.cwd()
const DECKS_DIR = path.join(ROOT, 'slide-decks')
const OUTPUT = path.join(ROOT, 'app/src/decks.js')

const BASE_PORT = 3030

const repoName = process.env.GITHUB_REPOSITORY
  ? process.env.GITHUB_REPOSITORY.split('/')[1]
  : ''

// ----------------- Helpers -----------------

function parseFrontmatter(md) {
  const match = md.match(/^---\s*\n([\s\S]*?)\n---/)
  if (!match) return {}

  const yaml = match[1]
  const meta = {}

  for (const line of yaml.split('\n')) {
    const m = line.match(/^(\w+)\s*:\s*(.+)$/)
    if (m) {
      const key = m[1]
      let value = m[2].trim()

      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1)
      }

      meta[key] = value
    }
  }

  return meta
}

function isDeck(name) {
  return fs.existsSync(path.join(DECKS_DIR, name, 'slides.md'))
}

// ----------------- Main -----------------

// Read decks in filesystem order
const rawDecks = fs
  .readdirSync(DECKS_DIR)
  .filter(d => fs.statSync(path.join(DECKS_DIR, d)).isDirectory())
  .filter(isDeck)

// Assign stable ports FIRST
const withPorts = rawDecks.map((id, index) => {
  const slidesPath = path.join(DECKS_DIR, id, 'slides.md')
  const md = fs.readFileSync(slidesPath, 'utf-8')
  const meta = parseFrontmatter(md)

  return {
    id,
    port: BASE_PORT + index,
    title: meta.title || id,
    description: meta.description || '',
    author: meta.author || 'Unknown',
    date: meta.date || '1970-01-01'
  }
})

// Now sort for display
withPorts.sort((a, b) => new Date(b.date) - new Date(a.date))

// Generate output
const output = `// AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-decks.js

const dev = import.meta.env.DEV

export default [
${withPorts
  .map(
    d => `  {
    id: "${d.id}",
    title: "${d.title.replace(/"/g, '\\"')}",
    description: "${d.description.replace(/"/g, '\\"')}",
    author: "${d.author.replace(/"/g, '\\"')}",
    date: "${d.date}",
    url: dev
      ? "http://localhost:${d.port}"
      : "/${repoName}/${d.id}/"
  }`
  )
  .join(',\n')}
]
`


fs.writeFileSync(OUTPUT, output)
console.log(`Generated ${withPorts.length} decks (stable ports, sorted by date)`)
