import fs from 'fs'
import path from 'path'

const ROOT = process.cwd()
const DECKS_DIR = path.join(ROOT, 'slide-decks')
const OUTPUT = path.join(ROOT, 'app/src/decks.js')

const BASE_PORT = 3030

const isDeck = name =>
  fs.existsSync(path.join(DECKS_DIR, name, 'slides.md'))

const decks = fs
  .readdirSync(DECKS_DIR)
  .filter(d => fs.statSync(path.join(DECKS_DIR, d)).isDirectory())
  .filter(isDeck)

let port = BASE_PORT

const entries = decks.map(id => {
  const metaPath = path.join(DECKS_DIR, id, 'deck.json')
  let meta = {}

  if (fs.existsSync(metaPath)) {
    meta = JSON.parse(fs.readFileSync(metaPath, 'utf-8'))
  }

  const assignedPort = port++

  return {
    id,
    port: assignedPort,
    title: meta.title || id,
    description: meta.description || 'Slidev presentation'
  }
})

const output = `// AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-decks.js

const dev = import.meta.env.DEV

export default [
${entries
  .map(
    d => `  {
    id: "${d.id}",
    title: "${d.title}",
    description: "${d.description}",
    thumbnail: dev
      ? "http://localhost:${d.port}/__slidev__/preview.png"
      : "/${d.id}/preview.png",
    url: dev
      ? "http://localhost:${d.port}"
      : "/${d.id}/"
  }`
  )
  .join(',\n')}
]
`

fs.writeFileSync(OUTPUT, output)
console.log(`Generated ${entries.length} decks`)
