// scripts/generate-decks.js
import fs from 'fs'
import path from 'path'

const ROOT = process.cwd()
const DECKS_DIR = path.join(ROOT, 'slide-decks')
const OUTPUT = path.join(ROOT, 'app/src/decks.js')

const BASE_PORT = 3030

// GitHub repo name (owner/Repo) → just "Repo"
const REPO_NAME = process.env.GITHUB_REPOSITORY
  ? process.env.GITHUB_REPOSITORY.split('/')[1]
  : ''

// ------------------------------------------------------------------
// Helper: parse very simple front‑matter (same as before)
// ------------------------------------------------------------------
function parseFrontmatter(md) {
  const match = md.match(/^---\s*\n([\s\S]*?)\n---/)
  if (!match) return {}
  const yaml = match[1]
  const meta = {}
  for (const line of yaml.split('\n')) {
    const m = line.match(/^(\w+)\s*:\s*(.+)$/)
    if (!m) continue
    const [, key, raw] = m
    let value = raw.trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    meta[key] = value
  }
  return meta
}

// ------------------------------------------------------------------
// Main
// ------------------------------------------------------------------
const rawDecks = fs
  .readdirSync(DECKS_DIR)
  .filter(d => fs.statSync(path.join(DECKS_DIR, d)).isDirectory())
  .filter(d => fs.existsSync(path.join(DECKS_DIR, d, 'slides.md')))

// Assign **stable** ports first (so dev URLs never change)
const decksWithPorts = rawDecks.map((id, idx) => {
  const slidesPath = path.join(DECKS_DIR, id, 'slides.md')
  const md = fs.readFileSync(slidesPath, 'utf-8')
  const meta = parseFrontmatter(md)

  return {
    id,
    port: BASE_PORT + idx,
    title: meta.title || id,
    description: meta.description || '',
    author: meta.author || 'Unknown',
    date: meta.date || '1970-01-01',
  }
})

// Sort for UI (newest first)
decksWithPorts.sort((a, b) => new Date(b.date) - new Date(a.date))

// ------------------------------------------------------------------
// Generate a tiny ES module that the SPA imports
// ------------------------------------------------------------------
const output = `// AUTO‑GENERATED – DO NOT EDIT
// Generated by scripts/generate-decks.js

const dev = import.meta.env.DEV

export default [
${decksWithPorts
  .map(
    d => `  {
    id: "${d.id}",
    title: "${d.title.replace(/"/g, '\\"')}",
    description: "${d.description.replace(/"/g, '\\"')}",
    author: "${d.author.replace(/"/g, '\\"')}",
    date: "${d.date}",
    url: dev
      ? "http://localhost:${d.port}"
      : "${REPO_NAME ? `/${REPO_NAME}/${d.id}/` : `/${d.id}/`}"
  }`
  )
  .join(',\n')}
]
`

fs.writeFileSync(OUTPUT, output)
console.log(`✅ Generated ${decksWithPorts.length} deck entries (stable ports, sorted by date)`)