name: Deploy pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive


      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Build Deck1
        run: npm run build:deck1 -- --base /${{github.event.repository.name}}/deck1
      
      - name: Build Deck2
        run: npm run build:deck2 -- --base /${{github.event.repository.name}}/deck2
      
      - name: Build Deck3
        run: npm run build:deck3 -- --base /${{github.event.repository.name}}/deck3
      
      - name: Build Deck4
        run: npm run build:deck4 -- --base /${{github.event.repository.name}}/deck4
      
      - name: Build Deck5
        run: npm run build:deck5 -- --base /${{github.event.repository.name}}/deck5

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4